name: mitt
description: Tiny functional event emitter / pubsub. Inspired by npm "mitt"
version: 1.0.3
homepage: https://github.com/anyone-developer

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
